site_name: CiviOffice
site_description: 'A guide for the CiviOffice.'
site_author: SYSTOPIA
repo_url: https://github.com/systopia/de.systopia.civioffice

theme:
  name: material

nav:
  - 'Introduction': index.md
  - 'Installation': installation.md
  - 'Configuration': configuration.md
  - 'Usage':
    - 'Working With Documents': usage/working-with-documents.md
    - 'Inserting dynamic content with "Live Snippets"': usage/inserting-content-with-live-snippets.md
    - 'Formatting and applying Smarty logic in tokens': usage/formatting-and-simple-syntax-html-conversion.md
    - 'Custom Fonts': usage/custom-fonts.md
    - 'Integrating With Donation Receipts': usage/integrating-with-donation-receipts.md
    - 'Sending Emails With Personalized Attachments': usage/integrating-with-mail-batch.md
  - 'Developer Information':
    - 'Modify Token Context': developer-information/modify-token-context.md
    - 'Custom Document Stores': developer-information/custom-document-stores.md
    - 'SearchKit Task for Custom Entities': developer-information/searchkit-task-custom-entities.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
